# Makefile
all: executable install clean build bundle zip

executable:
	chmod -R +x .

install:
	./install.sh

clean:
	./clean.sh

build:
	./build.sh

bundle:
	./bundle.sh

zip:
	./zip.sh	

.PHONY: all executable install clean build bundle zip

